 {
  turbo: false,
  interpolation: false,
  framerate: 30,
  highQualityPen: false,
  maxClones: 300,
  fencing: true,
  miscLimits: true,
  stageWidth: 480,
  stageHeight: 360,
  resizeMode: "preserve-ratio",
  autoplay: true,
  username: "player####",
  closeWhenStopped: false,
  projectId: "1006904939",
  custom: {
    css: "",
    js: ""
  },
  appearance: {
    background: "#000000",
    foreground: "#ffffff",
    accent: "#4dff9a"
  },
  loadingScreen: {
    progressBar: true,
    text: "Loading...",
    imageMode: "normal",
    image: null
  },
  controls: {
    greenFlag: {
      enabled: false
    },
    stopAll: {
      enabled: false
    },
    fullscreen: {
      enabled: false
    },
    pause: {
      enabled: false
    }
  },
  monitors: {
    editableLists: true,
    variableColor: "#1aff1d",
    listColor: "#fc662c"
  },
  compiler: {
    enabled: true,
    warpTimer: false
  },
  packagedRuntime: true,
  target: "nwjs-win64",
  app: {
    icon: null,
    packageName: "aquarium-simulator",
    windowTitle: "Aquarium Game",
    windowMode: "window",
    version: "1.0.0",
    escapeBehavior: "unfullscreen-only",
    windowControls: "default"
  },
  chunks: {
    gamepad: true,
    pointerlock: false
  },
  cloudVariables: {
    mode: "ws",
    cloudHost: "wss://clouddata.turbowarp.org",
    custom: {},
    specialCloudBehaviors: false,
    unsafeCloudBehaviors: false
  },
  cursor: {
    type: "custom",
    custom: {
      __isBlob: true,
      type: "",
      name: "nat686.cur",
      data: "AAACAAEAICAAAAAAAACoCAAAFgAAACgAAAAgAAAAQAAAAAEACAAAAAAAAAQAAAAAAAAAAAAAAAEAAAABAAAAAAAAIiIiAGZmAAAAAFUAAGZmAJlmAABmmQAAZpkzAP+ZMwD/zDMA/8xmAAAAzAAAmZkAAP+ZAGbMmQBm/5kAAMzMAAD/zAAAzP8AmczMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAECwsLCwsEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQDAwMDAwsLBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAcHBwcHAwMLBAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAEBwEHAQcHAwsEAAAAAAAAAAAAAAAAAAAAAAAABAQAAAQCAQIBBwEHAwsEAAAAAAAAAAAAAAAAAAAAAAQPBAAABAEBAQECBwcDCwQAAAAAAAAAAAAAAAAAAAAEDw0EAAAEAQEBAgEBBwMLBAAABAAAAAAAAAAAAAAABA8NBAAABAcBAQIBAgcHAwsEAAAEBAAAAAAAAAAAAAQPDQ4EAAQHAgECAQEBAQcDCwQAAAQSBAAAAAAAAAAEDw0OBAAEBwIEAQEBAQIHBwMLBAAABBIEAAAAAAAABA8EBAQEBAcCBAEFCQQEBAQEBAQAAAAEEg4EAAAAAAQEBAcHBwcHAgQBBQkEAAAAAAAAAAAAAAAEEg4EAAAEBwcHAgICAgIEAQUJBAAAAAAAAAAAAAAAAAQSDgcEBAcCAgIBAQEBCAEFCgQABAQEAAAAAAAAAAAABBMHBwQHAgEBBQgBBQkBBQkBBAQODA4EAAAAAAAAAAAABBMEBwIBAQUJAQEIAQUKAQQQAQQREQQAAAAAAAAAAAAABAICAQEFCAMFCgEFCAEFBA4ODA4EAAAAAAAAAAAAAAQBAQEBBQoDAwkBBQkBBQkEAQQREQQAAAAAAAAAAAAEAwEBAQEIAwUJAQUIAQUJBBAODA4EAAAAAAAAAAAAAAQDAQICAQEFCAEFCQEFCQEEAQQREQQAAAAAAAAAAAAABAMCBgcCAQEFAQoBBQkBBBAODA4EAAAAAAAAAAAAAAQDAgYHBwcCAQUIAQUIAQkEAQQREQQAAAAAAAAAAAAABAMCBgcHBwIBBQUFCAEJBBAMDA4EAAAAAAAAAAAAAAQDAwIGBwcCAQEFBQgBCQQBBA4REQQAAAAAAAAAAAAABAMDAgYHBwIBAQUIAQkEEA4MDA4EAAAAAAAAAAAAAAAEAwMQEAcCAQEDBQUIBBAEBA4REQQAAAAAAAAAAAAABAMDEQEBEAEBAQUDBAQBDg4MDA4EAAAAAAAAAAAAAAAEAwMRAQEQAQEBBAQEEA4EBBERBAAAAAAAAAAAAAAAAAQDAwEREQEBBAQAAAAEBBERDgQAAAAAAAAAAAAAAAAABAMDAQEBBAQAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAABAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///B////gH///4A///+AH//9gB//+YAP//GAD//hgA3/wwAM/4IADH8EAAx+AAAcPAAP/hgAH/4AACP+AAAB/wAAAf+AAAP/AAAD/gAAB/4AAAf+AAAP/AAAD/wAAB/4AAAf+AAAP/gAAD/wAAB/8AAA//ADgf/wD+P/+D////"
    },
    center: {
      x: 0,
      y: 0
    }
  },
  steamworks: {
    appId: "480",
    onError: "warning"
  },
  extensions: [],
  bakeExtensions: true,
  maxTextureDimension: 2048
}
function changeContent() {
document.getElementById("demo").innerHTML = "Content changed!";
}